---
log:
  level: debug

gitlab:
  url: http://nix:81/
  token: <your_token>

# Pull jobs related metrics on all projects
project_defaults:
  pull:
    pipeline:
      jobs:
        enabled: true

wildcards:
  - {}
